### ISSUE TITLE
卧槽666

### ISSUE THREAD

**Issue by EyreFree** [timothyqiu/python-swjsq#1]
大神好厉害。。。OSX 的么

**Comment by timothyqiu** [comment]
本意是在 Linux 路由器之类的东西上跑，不过 OS X 也可以跑。
另外不想 pip 安装的话，可以 clone 下来，然后在工程根目录用 `python -m swjsq.cli` 运行，用户名密码的设置见 `README.rst`。

**Comment by EyreFree** [comment]
迅雷快鸟 是开源了么。。。

**Comment by timothyqiu** [comment]
没有，可以嗅探 + 反编译。主要工作是 https://github.com/fffonion/Xunlei-Fastdick 这个项目做的，我 Fork 出来做的维护和修改，提交历史里有。
