### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ghost** [timothyqiu/python-swjsq#2]
8月10号开始出现的问题，超级会员。pc端提速正常。
![2](https://user-images.githubusercontent.com/9400373/29381223-0e0818b0-82fb-11e7-9f00-53b56d975421.png)
当天，我测试Xunlei-FastDick脚本也出现了报错，虽然报错内容不同，但应该是同一问题。请参考https://github.com/fffonion/Xunlei-Fastdick/issues/104  怀疑是超级会员的原因?或某些api发生变动了?

**Comment by ghost** [comment]
具体现象提供如下，以便调试。
I 第一次启动脚本 正常提速 ctrl+c结束掉之后 再次运行脚本 会报此错误。
II 第一次启动脚本 正常提速 等待timesleep直到第二次提速 会报此错误。
等待提速效果失效（约几个小时） 可以再次执行，否则中途一直会报此错误。

**Comment by timothyqiu** [comment]
找了一个超级会员账号试了下，无法重现，可能和地区运营商有关。

所幸此处的内容缺失只影响 Log 输出，不影响提速功能。我在 `develop` 分支上改了一下，处理了 `bandwidth` 为空的情况，同时输出了此时的日志。

暂时还没有推送到 PyPI，你可以试一下安装仓库里的最新版本。卸载原有版本后执行：

    pip install git+https://github.com/timothyqiu/python-swjsq.git@develop

应该不会报错，可以正常加速了。但是原来显示速率的地方会显示 `Down <UNKNOWN>`，还会有类似

    2017-08-17 20:15:00 WARNING No `bandwidth` field: {.....}

的输出，如果方便的话，请反馈一下这行日志。🍻

**Comment by ghost** [comment]
![pr_fbv hlz d5ozzzm l21_lim limit](https://user-images.githubusercontent.com/9400373/29416840-eed38afc-8399-11e7-9c86-9b689c3ed78f.png)
从提速后的测速结果来看是成功的，我挂一天看看，如果有其他问题明天再反馈给您，谢谢！

**Comment by ghost** [comment]
正常使用，没发现别的问题了。
